export function ControlPanel({ sim }) {
  const hasSeed = Boolean(sim.seed)
  const running = sim.process.phase !== 'SELECT_SEED' && sim.process.phase !== 'COMPLETE'
  return <aside className="control-panel">
    <div className="panel-title"><span className="panel-icon">⚙</span><div><h2>Simulation Controls</h2><p>Configure the experiment</p></div></div>
    <section className="control-section"><label className="section-label">GRID SIZE</label><div className="segmented">{[8, 16].map((n) => <button key={n} className={sim.size === n ? 'active' : ''} onClick={() => sim.changeSize(n)}>{n} × {n}</button>)}</div></section>
    <section className="control-section"><label className="section-label">GENERATE IMAGE</label><button className="wide-button secondary" onClick={sim.generate}>↻ Generate New Image</button><p className="microcopy">Organic intensity regions are generated for meaningful growth.</p></section>
    <section className="control-section"><label className="section-label">SEED SELECTION</label><p className="instruction">⌁ Click a pixel in the grayscale image to select the seed.</p><div className="seed-info">{hasSeed ? <><span><b>Row</b> {sim.seed.row + 1}</span><span><b>Column</b> {sim.seed.col + 1}</span><span><b>Intensity</b> {sim.seed.intensity}</span></> : <span className="muted">No seed selected</span>}</div></section>
    <section className="control-section"><label className="section-label">CONNECTIVITY</label>{[4, 8].map((n) => <label key={n} className="radio-row"><input type="radio" checked={sim.connectivity === n} onChange={() => sim.setConnectivity(n)} /> <span>{n}-Connectivity</span><small>{n === 4 ? 'N · S · E · W' : 'Includes diagonal neighbours'}</small></label>)}{hasSeed && <p className="reset-note">Changing connectivity restarts the simulation.</p>}</section>
    <section className="control-section"><div className="range-heading"><label className="section-label">THRESHOLD</label><output>Threshold = {sim.threshold}</output></div><input className="threshold-slider" type="range" min="0" max="100" value={sim.threshold} onChange={(e) => sim.setThreshold(Number(e.target.value))} /><div className="range-endpoints"><span>0</span><span>100</span></div><input className="number-input" type="number" min="0" max="100" value={sim.threshold} onChange={(e) => sim.setThreshold(Math.max(0, Math.min(100, Number(e.target.value))))} /></section>
    <section className="control-section simulation-buttons"><label className="section-label">SIMULATION CONTROLS</label><div className="button-grid"><button className="primary" onClick={sim.step} disabled={!hasSeed || sim.process.phase === 'COMPLETE'}>Step <kbd>→</kbd></button><button onClick={() => sim.setIsPlaying(true)} disabled={!hasSeed || sim.process.phase === 'COMPLETE'}>▶ Play</button><button onClick={() => sim.setIsPlaying(false)} disabled={!sim.isPlaying}>Ⅱ Pause</button><button onClick={sim.reset}>↺ Reset</button></div>{!hasSeed && <p className="reset-note">Please select a seed pixel to begin.</p>}<div className="speed-row"><span>Speed</span>{['slow', 'medium', 'fast'].map((s) => <button key={s} className={sim.speed === s ? 'selected-speed' : ''} onClick={() => sim.setSpeed(s)}>{s}</button>)}</div></section>
    <div className={`status-chip ${sim.process.phase === 'COMPLETE' ? 'done' : running ? 'running' : ''}`}>{sim.process.phase === 'COMPLETE' ? '● Complete' : sim.isPlaying ? '● Playing' : '● Ready'}</div>
  </aside>
}
